export const ASSESSMENT_MINUTES = 20;

export const CATEGORIES = [
  { name: "Quantitative Aptitude", short: "Quantitative", code: "01", description: "Numbers, ratios and practical calculation" },
  { name: "Logical Reasoning", short: "Reasoning", code: "02", description: "Patterns, deduction and structured thinking" },
  { name: "Verbal Ability", short: "Verbal", code: "03", description: "Vocabulary, grammar and clear meaning" },
  { name: "Data Interpretation", short: "Data", code: "04", description: "Reading tables and comparing evidence" },
];

const salesTable = {
  heading: "Quarterly unit sales (in thousands)",
  columns: ["Region", "Q1", "Q2", "Q3"],
  rows: [
    ["North", "120", "150", "180"],
    ["South", "100", "130", "170"],
    ["East", "90", "120", "150"],
  ],
};

export const QUESTION_BANK = [
  {
    id: "Q01",
    category: "Quantitative Aptitude",
    prompt: "A jacket marked at $800 is sold at a 15% discount. What is its sale price?",
    options: ["$660", "$670", "$680", "$700"],
    answerIndex: 2,
    explanation: "The discount is 15% of $800, or $120. Subtracting $120 from $800 gives a sale price of $680.",
  },
  {
    id: "Q02",
    category: "Quantitative Aptitude",
    prompt: "The ratio of red to blue tiles is 3:5. If there are 64 tiles altogether, how many are red?",
    options: ["18", "24", "32", "40"],
    answerIndex: 1,
    explanation: "The ratio has 3 + 5 = 8 equal parts. Each part is 64 ÷ 8 = 8 tiles, so the red tiles number 3 × 8 = 24.",
  },
  {
    id: "Q03",
    category: "Quantitative Aptitude",
    prompt: "The mean of 12, 20, 15 and x is 18. What is x?",
    options: ["21", "23", "25", "27"],
    answerIndex: 2,
    explanation: "Four values with a mean of 18 have a total of 4 × 18 = 72. The known values total 47, so x = 72 − 47 = 25.",
  },
  {
    id: "Q04",
    category: "Quantitative Aptitude",
    prompt: "A 180-metre train passes a signal post in 12 seconds. What is its speed in kilometres per hour?",
    options: ["45 km/h", "48 km/h", "54 km/h", "60 km/h"],
    answerIndex: 2,
    explanation: "The train covers 180 ÷ 12 = 15 metres per second. Multiply by 3.6 to convert to kilometres per hour: 15 × 3.6 = 54 km/h.",
  },
  {
    id: "Q05",
    category: "Logical Reasoning",
    prompt: "What number comes next in the sequence? 2, 6, 12, 20, 30, __",
    options: ["36", "40", "42", "44"],
    answerIndex: 2,
    explanation: "The differences are +4, +6, +8 and +10. The pattern adds consecutive even numbers, so the next difference is +12 and the answer is 42.",
  },
  {
    id: "Q06",
    category: "Logical Reasoning",
    prompt: "All roses are flowers. Some flowers fade quickly. Which statement must be true?",
    options: ["Some roses fade quickly", "All roses are flowers", "No roses fade quickly", "All flowers are roses"],
    answerIndex: 1,
    explanation: "The first statement directly establishes that every rose belongs to the group of flowers. The second statement does not tell us whether any roses are among the flowers that fade quickly.",
  },
  {
    id: "Q07",
    category: "Logical Reasoning",
    prompt: "What letter comes next? A, C, F, J, O, __",
    options: ["T", "U", "V", "W"],
    answerIndex: 1,
    explanation: "The letter positions increase by +2, +3, +4 and +5. The next increase is +6: O is the 15th letter, and 15 + 6 = 21, which is U.",
  },
  {
    id: "Q08",
    category: "Logical Reasoning",
    prompt: "A student faces north, turns right, turns right again, then turns left. Which direction is the student facing?",
    options: ["North", "South", "East", "West"],
    answerIndex: 2,
    explanation: "Starting north, the first right turn faces east. A second right turn faces south, and a left turn from south faces east.",
  },
  {
    id: "Q09",
    category: "Verbal Ability",
    prompt: "Which word is closest in meaning to “concise”?",
    options: ["Brief", "Unclear", "Detailed", "Persuasive"],
    answerIndex: 0,
    explanation: "Concise means expressing an idea clearly in few words. “Brief” is the closest match.",
  },
  {
    id: "Q10",
    category: "Verbal Ability",
    prompt: "Choose the correct verb: “Neither the analysts nor the manager ___ available for the meeting.”",
    options: ["were", "are", "was", "have been"],
    answerIndex: 2,
    explanation: "With “neither … nor,” the verb usually agrees with the nearer subject. “Manager” is singular, so “was” is correct.",
  },
  {
    id: "Q11",
    category: "Verbal Ability",
    prompt: "Complete the sentence: “The board ___ the proposal after reviewing the evidence.”",
    options: ["commending", "commended", "commend", "commendation"],
    answerIndex: 1,
    explanation: "The sentence describes a completed action in the past. “Commended” is the correct past-tense verb.",
  },
  {
    id: "Q12",
    category: "Verbal Ability",
    prompt: "Which sentence uses “principle” correctly?",
    options: ["The principle reason was cost.", "She kept her principle appointment.", "The school follows a clear principle of fairness.", "He is the principle of the college."],
    answerIndex: 2,
    explanation: "“Principle” is a rule or belief. A “principal” is a person in charge or something of primary importance, so only the third sentence uses “principle” correctly.",
  },
  {
    id: "Q13",
    category: "Data Interpretation",
    prompt: "Across all three regions, how many thousand units were sold in Q2?",
    options: ["380", "390", "400", "410"],
    answerIndex: 2,
    stimulus: salesTable,
    explanation: "Add the Q2 figures for North, South and East: 150 + 130 + 120 = 400 thousand units.",
  },
  {
    id: "Q14",
    category: "Data Interpretation",
    prompt: "What was the percentage increase in North's sales from Q1 to Q3?",
    options: ["40%", "45%", "50%", "60%"],
    answerIndex: 2,
    stimulus: salesTable,
    explanation: "North increased by 180 − 120 = 60 thousand units. Relative to Q1, 60 ÷ 120 × 100 = 50%.",
  },
  {
    id: "Q15",
    category: "Data Interpretation",
    prompt: "How many thousand units did East sell across Q1, Q2 and Q3 combined?",
    options: ["330", "350", "360", "390"],
    answerIndex: 2,
    stimulus: salesTable,
    explanation: "East's three quarterly figures total 90 + 120 + 150 = 360 thousand units.",
  },
  {
    id: "Q16",
    category: "Data Interpretation",
    prompt: "Which region had the largest absolute sales increase from Q1 to Q3?",
    options: ["North", "South", "East", "All three increased equally"],
    answerIndex: 1,
    stimulus: salesTable,
    explanation: "North increased by 60, South by 70, and East by 60 thousand units. South had the largest absolute increase.",
  },
];
